In [60]:
import numpy as np


In [61]:
import math

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

### 1.

In [3]:
len(a[a < 0])

4

### 2.

In [4]:
len(a[a > 0])

5

### 3.

In [5]:
len(a[(a > 0) & (a % 2 == 0)])

3

### 4.

In [6]:
a1 = a + 3
a1

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [7]:
len(a1[a1 > 0])

10

### 5.

In [8]:
b = a ** 2
b

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [9]:
b.mean()

74.0

In [10]:
b.std()

144.0243035046516

### 6.

In [11]:
c = a - a.mean()
c

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7.

In [12]:
z = ((a-(a.mean()))/a.std())
# also could utilize above variable: z = (c/a.std())
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### 8.

In [13]:
import numpy as np

In [14]:
import statistics

In [15]:

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Use python's built in functionality/operators to determine the following:
a = np.array(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = a.sum()
sum_of_a


55

In [17]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = a.min()
min_of_a


1

In [18]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = a.max()
max_of_a


10

In [19]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = a.mean()
mean_of_a


5.5

In [20]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = a.prod()
product_of_a


3628800

In [21]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = a ** 2
squares_of_a


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [22]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = a[a % 2 != 0]
odds_in_a


array([1, 3, 5, 7, 9])

In [23]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [24]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [25]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
    
sum_of_b = b.sum()
sum_of_b


33

In [26]:
# Exercise 2 - refactor the following to use numpy.  

min_of_b = b.min()
min_of_b


3

In [27]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

max_of_b = b.max()
max_of_b


8

In [28]:
# Exercise 4 - refactor the following using numpy to find the mean of b

mean_of_b = b.mean()
mean_of_b



5.5

In [29]:
import itertools  


In [30]:
from itertools import product

In [31]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
      
product_of_b = b.prod()
product_of_b



20160

In [32]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
squares_of_b = b ** 2
squares_of_b



array([[ 9, 16, 25],
       [36, 49, 64]])

In [33]:
# Exercise 7 - refactor using numpy to determine the odds_in_b

odds_in_b = b[b % 2 != 0]
odds_in_b


array([3, 5, 7])

In [34]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers

evens_in_b = b[b % 2 == 0]
evens_in_b



array([4, 6, 8])

In [35]:
# Exercise 9 - print out the shape of the array b.

b.shape


(2, 3)

In [36]:
# Exercise 10 - transpose the array b.

b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [37]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

print('b reshaped to (1, 6): {}.'.format(b.reshape((1, 6))))


b reshaped to (1, 6): [[3 4 5 6 7 8]].


In [38]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

print('b reshaped to (6, 1):\n{}.'.format(b.reshape((6, 1))))

b reshaped to (6, 1):
[[3]
 [4]
 [5]
 [6]
 [7]
 [8]].


In [64]:
## Setup 3
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
print(c.min())

print(c.max())

print(c.sum())

print(c.prod())


1
9
45
362880


In [65]:
# Exercise 2 - Determine the standard deviation of c.

print('Standard deviation of c: {}.'.format(c.std()))



Standard deviation of c: 2.581988897471611.
Variance of c: 6.666666666666667.
Shape of c: (3, 3).
c transposed:
[[1 4 7]
 [2 5 8]
 [3 6 9]].
Dot product of c with c:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]].
Sum of c times c transposed: 261.
Product of c times c transposed: 131681894400.


In [66]:
# Exercise 3 - Determine the variance of c.

print('Variance of c: {}.'.format(c.var()))



Variance of c: 6.666666666666667.


In [67]:
# Exercise 4 - Print out the shape of the array c

print('Shape of c: {}.'.format(c.shape))



Shape of c: (3, 3).


In [68]:
# Exercise 5 - Transpose c and print out transposed result.

print('c transposed:\n{}.'.format(c.transpose()))



c transposed:
[[1 4 7]
 [2 5 8]
 [3 6 9]].


In [69]:
# Exercise 6 - Get the dot product of the array c with c. 
print('Dot product of c with c:\n{}.'.format(np.dot(c, c)))



Dot product of c with c:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]].


In [70]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
print('Sum of c times c transposed: {}.'.format(np.sum(c * c.transpose())))




Sum of c times c transposed: 261.


In [71]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

print('Product of c times c transposed: {}.'.format(np.product(c * c.transpose())))





Product of c times c transposed: 131681894400.


In [82]:
## Setup 4
d = np.array([[90, 30, 45, 0, 120, 180],
              [45, -90, -30, 270, 90, 0],
              [60, 45, -45, 90, -45, 180]])

In [81]:
# Exercise 1 - Find the sine of all the numbers in d
print('Sin values of d:\n{}.\n\n'.format(np.sin(d)))



Sin values of d:
[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]].




In [80]:
# Exercise 2 - Find the cosine of all the numbers in d
print('Cos values of d:\n{}.\n\n'.format(np.cos(d)))



Cos values of d:
[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]].




In [79]:
# Exercise 3 - Find the tangent of all the numbers in d

print('Tan values of d:\n{}.\n\n'.format(np.tan(d)))



Tan values of d:
[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]].




In [78]:
# Exercise 4 - Find all the negative numbers in d

print('Negative numbers in d: {}.\n'.format(d[d < 0]))




Negative numbers in d: [-90 -30 -45 -45].



In [77]:
# Exercise 5 - Find all the positive numbers in d
print('Positive numbers in d: {}.\n'.format(d[d > 0]))



Positive numbers in d: [ 90  30  45 120 180  45 270  90  60  45  90 180].



In [76]:
# Exercise 6 - Return an array of only the unique numbers in d.

print('Unique numbers in d: {}.\n'.format(np.unique(d)))



Unique numbers in d: [-90 -45 -30   0  30  45  60  90 120 180 270].



In [75]:
# Exercise 7 - Determine how many unique numbers there are in d.
print('Shape of d: {}.\n'.format(np.shape(d)))



Shape of d: (3, 6).



In [74]:
# Exercise 8 - Print out the shape of d.

print('d transposed:\n{}.\n'.format(np.transpose(d)))







d transposed:
[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]].



In [73]:
# Exercise 9 - Transpose and then print out the shape of d.
print('d reshaped to (9, 2):\n{}.'.format(np.reshape(d, (9, 2))))


d reshaped to (9, 2):
[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]].
