In [2]:
import numpy as np


In [37]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

### 1.

In [6]:
len(a[a < 0])

4

### 2.

In [7]:
len(a[a > 0])

5

### 3.

In [14]:
len(a[(a > 0) & (a % 2 == 0)])

3

### 4.

In [18]:
a1 = a + 3
a1

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [19]:
len(a1[a1 > 0])

10

### 5.

In [38]:
b = a ** 2
b

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [39]:
b.mean()

74.0

In [40]:
b.std()

144.0243035046516

### 6.

In [25]:
c = a - a.mean()
c

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7.

In [28]:
z = ((a-(a.mean()))/a.std())
# also could utilize above variable: z = (c/a.std())
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### 8.

In [6]:
import numpy as np

In [7]:
import statistics

In [41]:

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Use python's built in functionality/operators to determine the following:
a = np.array(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = a.sum()
sum_of_a


55

In [43]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = a.min()
min_of_a


1

In [44]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = a.max()
max_of_a


10

In [45]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = a.mean()
mean_of_a


5.5

In [50]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = a.prod()
product_of_a


3628800

In [51]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = a ** 2
squares_of_a


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [52]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = a[a % 2 != 0]
odds_in_a


array([1, 3, 5, 7, 9])

In [53]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [41]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [10]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
    
sum_of_b = b.sum()
sum_of_b


33

In [12]:
# Exercise 2 - refactor the following to use numpy.  

min_of_b = b.min()
min_of_b


3

In [13]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

max_of_b = b.max()
max_of_b


8

In [14]:
# Exercise 4 - refactor the following using numpy to find the mean of b

mean_of_b = b.mean()
mean_of_b



5.5

In [22]:
import itertools  


In [23]:
from itertools import product

In [26]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
      
product_of_b = b.prod()
product_of_b



20160

In [27]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
squares_of_b = b ** 2
squares_of_b



array([[ 9, 16, 25],
       [36, 49, 64]])

In [28]:
# Exercise 7 - refactor using numpy to determine the odds_in_b

odds_in_b = b[b % 2 != 0]
odds_in_b


array([3, 5, 7])

In [29]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers

evens_in_b = b[b % 2 == 0]
evens_in_b



array([4, 6, 8])

In [42]:
# Exercise 9 - print out the shape of the array b.

b.shape


(2, 3)

In [43]:
# Exercise 10 - transpose the array b.

b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)



In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)



In [ ]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.



In [ ]:
# Exercise 2 - Determine the standard deviation of c.



In [ ]:
# Exercise 3 - Determine the variance of c.



In [ ]:
# Exercise 4 - Print out the shape of the array c



In [ ]:
# Exercise 5 - Transpose c and print out transposed result.



In [ ]:
# Exercise 6 - Get the dot product of the array c with c. 



In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261



In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.




In [ ]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d



In [ ]:
# Exercise 2 - Find the cosine of all the numbers in d



In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d



In [ ]:
# Exercise 4 - Find all the negative numbers in d



In [ ]:
# Exercise 5 - Find all the positive numbers in d



In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.



In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.



In [ ]:
# Exercise 8 - Print out the shape of d.



In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

